name: my_school
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  api_service:
    git:
      url: https://github.com/hamidjalili59/api_service.git
      ref: main
  auto_route: ^5.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  database_service:
    git:
      url: https://github.com/hamidjalili59/database_service.git
  dio: ^5.1.0
  dropdown_search: ^5.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1 
  freezed_annotation: ^2.2.0
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.11
  flutter_screenutil: ^5.5.4
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^1.5.3
  json_annotation: ^4.7.0
  logger: ^1.1.0
  lottie: ^1.4.3
  ndialog: ^4.2.0
  pin_code_fields: ^7.4.0
  pull_to_refresh: ^2.0.0
  rename: ^2.0.1
  tuple: ^2.0.1

dev_dependencies:
  auto_route_generator: ^5.0.2
  build_runner: ^2.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0

  hive_generator: ^1.1.3
  injectable_generator: ^1.5.4
  json_serializable: ^6.5.1

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/school_appicon.png"
  min_sdk_android: 21

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/icons/student/
    - assets/icons/teacher/
    - assets/icons/course/
    - assets/background/
    - assets/lotties/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
